# Generated by Django 4.0 on 2022-07-24 22:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostsXlex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('img_destaque', models.ImageField(blank=True, default=1, null=True, upload_to='images/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=200)),
                ('key_word', models.CharField(max_length=50)),
                ('meta_description', models.TextField(max_length=150)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('category', models.ForeignKey(default='XLEX', max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='app_posts.category')),
            ],
        ),
    ]
