# Generated by Django 4.0 on 2022-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0004_alter_postsxlex_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='excerpt',
            field=models.CharField(default='NonNOnnn', max_length=150),
        ),
        migrations.AlterField(
            model_name='postsxlex',
            name='category',
            field=models.CharField(choices=[('TST', 'TST'), ('STJ', 'STJ'), ('Suprema Corte', 'Suprema Corte'), ('News', 'News'), ('International Laws', 'International Laws')], default='XLEX', max_length=100),
        ),
    ]
