# Generated by Django 4.0 on 2022-07-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0005_category_excerpt_alter_postsxlex_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsxlex',
            name='category',
            field=models.ForeignKey(choices=[('TST', 'TST'), ('STJ', 'STJ'), ('Suprema Corte', 'Suprema Corte'), ('News', 'News'), ('International Laws', 'International Laws')], default='XLEX', max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='app_posts.category'),
        ),
    ]
