# Generated by Django 4.0 on 2022-07-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0009_alter_postsxlex_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsxlex',
            name='category',
            field=models.CharField(choices=[('Supremo Tribunal Federal', 'Supremo Tribunal Federal'), ('Superior Tribunal de Justiça', 'Superior Tribunal de Justiça')], default='XLEX', max_length=100),
        ),
    ]
