# Generated by Django 4.0 on 2022-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0011_alter_category_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='excerpt',
            field=models.CharField(default='Description...', max_length=150),
        ),
    ]
