# Generated by Django 4.0 on 2022-07-28 15:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('excerpt', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('excerpt', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.CharField(max_length=255)),
                ('banca_question', models.CharField(default='Undefined', max_length=255)),
                ('materia_question', models.CharField(default='Undefined', max_length=255)),
                ('question_ask', models.TextField(blank=True, null=True)),
                ('alternativa_a', models.CharField(max_length=1000)),
                ('alternativa_b', models.CharField(max_length=1000)),
                ('alternativa_c', models.CharField(max_length=1000)),
                ('alternativa_d', models.CharField(max_length=1000)),
                ('alternativa_e', models.CharField(max_length=1000)),
                ('alternativa_correta', models.CharField(max_length=1000)),
                ('fundamentacao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('lei_question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('jurisprudencia_question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tags_question', models.CharField(max_length=200)),
                ('meta_question', models.TextField(max_length=150)),
                ('key_word', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
