# Generated by Django 4.0 on 2022-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0002_alter_question_banca_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='materia_question',
            field=models.CharField(choices=[('Direito Civil', 'Direito Civil'), ('Etica', 'Etica'), ('Direito Constitucional', 'Direito Constitucional')], default='Undefined', max_length=255),
        ),
    ]
