# Generated by Django 4.0 on 2022-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0003_alter_question_materia_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='materia_question',
            field=models.CharField(choices=[('Direito Civil', 'Direito Civil'), ('Direito Constitucional', 'Direito Constitucional'), ('Ética', 'Ética')], default='Undefined', max_length=255),
        ),
    ]
