# Generated by Django 4.0 on 2022-07-29 00:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumulaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('excerpt', models.CharField(default='Description...', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SumulaTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('excerpt', models.CharField(default='Description...', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sumulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sumula', models.CharField(max_length=120)),
                ('sumula_tribunal', models.CharField(default='XLEX', max_length=100)),
                ('sumula_materia', models.CharField(default='XLEX', max_length=100)),
                ('content_sumula', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tags_sumula', models.CharField(max_length=200)),
                ('key_word', models.CharField(max_length=50)),
                ('meta_Sumula', models.TextField(max_length=150)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
