# Generated by Django 4.0 on 2022-07-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumulas', '0002_alter_sumulas_sumula_materia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sumulas',
            old_name='meta_Sumula',
            new_name='meta_sumula',
        ),
        migrations.AlterField(
            model_name='sumulas',
            name='sumula_materia',
            field=models.CharField(choices=[('Férias', 'Férias'), ('Contratos', 'Contratos'), ('ADI', 'ADI'), ('Direito Fundamentais', 'Direito Fundamentais')], default='XLEX', max_length=100),
        ),
    ]
