# Generated by Django 4.0 on 2022-07-29 02:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumulas', '0003_rename_meta_sumula_sumulas_meta_sumula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumulas',
            name='fundamentacao_sumula',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Sorry', null=True),
        ),
    ]
