# Generated by Django 4.0 on 2022-07-26 23:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireitoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('excerpt', models.CharField(default='Sorry', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('excerpt', models.CharField(default='Sorry', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CasoConcreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_caso', models.CharField(max_length=120)),
                ('img_caso', models.ImageField(blank=True, default=1, null=True, upload_to='images/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('direito_caso', models.CharField(default='XLEX', max_length=100)),
                ('materia_caso', models.CharField(default='XLEX', max_length=100)),
                ('meta_caso', models.TextField(max_length=150)),
                ('content_caso', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('lei_caso', models.TextField(default='Sorry')),
                ('jurisprudencia_caso', models.TextField(default='Sorry')),
                ('tags_caso', models.CharField(max_length=200)),
                ('key_word', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
