# Generated by Django 4.0 on 2022-07-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoconcreto',
            name='direito_caso',
            field=models.CharField(choices=[('Direito Civil', 'Direito Civil'), ('Direito Penal', 'Direito Penal'), ('Direito Tributário', 'Direito Tributário'), ('Direito Constitucional', 'Direito Constitucional')], default='XLEX', max_length=100),
        ),
        migrations.AlterField(
            model_name='casoconcreto',
            name='materia_caso',
            field=models.CharField(choices=[('Filosofia Aplicada ao Direito', 'Filosofia Aplicada ao Direito'), ('Direito Civil I', 'Direito Civil I'), ('Direito Civil II', 'Direito Civil II'), ('Direito Penal I', 'Direito Penal I'), ('Direito Penal II', 'Direito Penal II'), ('Constitucional I', 'Constitucional I')], default='XLEX', max_length=100),
        ),
    ]
