# Generated by Django 4.0 on 2022-07-27 05:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casos', '0004_alter_casoconcreto_lei_caso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoconcreto',
            name='jurisprudencia_caso',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
